### PR TITLE
Added resources for Q Optimisation

### PR DESCRIPTION
**Pull request by Sashe17**
### All Submissions:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/QForestCommunity/launchpad/pulls) for the same update/change?
* [x] The commit message is descriptive enough to convey what you are trying to contribute.

* **What kind of change does this PR introduce?** (Is it a new learning resource, tutorial or something else?)
Resources for Quantum Optimisation

* **What issue is this tackling?** (Link to an open issue here)

### CODE REVIEW

**Review by MadhavJivrajani — COMMENTED** [review]
Looks like a great starting point. 
I think the DWave documentation you added covers it but assuming its someone completely new to the field, would a video resource such as [this](https://www.youtube.com/playlist?list=PLPvKnT7dgEsvVQwGgrlUVXBa2J6PAW8a4) help along with official documentation?

**Comment by Sashe17** [comment]
> Looks like a great starting point.
> I think the DWave documentation you added covers it but assuming its someone completely new to the field, would a video resource such as [this](https://www.youtube.com/playlist?list=PLPvKnT7dgEsvVQwGgrlUVXBa2J6PAW8a4) help along with official documentation?

Sure, the documentation is fairly basic it just looks complex initially, but i can add it, extra info no harm

**Comment by MadhavJivrajani** [comment]
Alright, sounds good. 
Should points one and two be swapped to make sure resources are in a topological order of learning? Or are they independent in w.r.t. to each other?

**Comment by MadhavJivrajani** [comment]
@Sashe17 ?

**Pull request merged**
