### PR TITLE
Added introductory resources in a new Quantum Hardware folder 

### PR DESCRIPTION
**Pull request by mugdhapattnaik**
### All Submissions:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/QForestCommunity/launchpad/pulls) for the same update/change?
* [x] The commit message is descriptive enough to convey what you are trying to contribute.

* **What kind of change does this PR introduce?** (Is it a new learning resource, tutorial or something else?)
New learning resource 

* **What issue is this tackling?** (https://github.com/QForestCommunity/launchpad/issues/1)

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
Looks like a good starting point, could each bullet point have a brief description as to what the link entails?
In the meanwhile, I'll try and find a few resources to add to your existing collection as well.

**Comment by mugdhapattnaik** [comment]
Sure, will add the descriptions.

**Comment by MadhavJivrajani** [comment]
There's an [upcoming course](https://www.edx.org/course/hardware-of-quantum-computer) on edX on the hardware of quantum computers. If it looks good to you, maybe add it to the list!

**Comment by mugdhapattnaik** [comment]
> There's an [upcoming course](https://www.edx.org/course/hardware-of-quantum-computer) on edX on the hardware of quantum computers. If it looks good to you, maybe add it to the list!

Have enrolled myself in this course to check out the material. Will need some more time to go through it all. If the current collection of material looks good then is it okay if we could go ahead with this for now and I can send in another pull request updated with details of the course?

**Comment by MadhavJivrajani** [comment]
> > There's an [upcoming course](https://www.edx.org/course/hardware-of-quantum-computer) on edX on the hardware of quantum computers. If it looks good to you, maybe add it to the list!
> 
> Have enrolled myself in this course to check out the material. Will need some more time to go through it all. If the current collection of material looks good then is it okay if we could go ahead with this for now and I can send in another pull request updated with details of the course?

Sounds good :smile:

**Pull request merged**
