### PR TITLE
Added a QML folder and a tutorial guidelines file

### PR DESCRIPTION
**Pull request by SashwatAnagolum**
### All Submissions:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/QForestCommunity/launchpad/pulls) for the same update/change?
* [x] The commit message is descriptive enough to convey what you are trying to contribute.

* **What kind of change does this PR introduce?** (Is it a new learning resource, tutorial or something else?)

Created a tutorial guidelines file, and a quantum machine learning resource folder.

* **What issue is this tackling?** (#1)

### CODE REVIEW

**Comment by SashwatAnagolum** [comment]
The QML file is still very skeletal, definitely needs more stuff, as well as descriptions of each link, but I think this is a good starting point.

**Review by MadhavJivrajani — APPROVED** [review]
Greating starting point!

**Comment by MadhavJivrajani** [comment]
@SashwatAnagolum We need to keep the naming of the folders uniform, so since its only meant for resources, maybe name it `Quantum Machine Learning` instead of `quantumMachineLearning`, just for the sake of increased readability.

**Review by MadhavJivrajani — CHANGES_REQUESTED** [review]
Looks good!
Maybe add an explicit link to the qiksit textbook's section on single-qubit gates or more specifically Ry and controlled gates.

Also, try adding a cell that gives the output of `qc.draw()` to show the circuit constructed.

**Review by MadhavJivrajani — APPROVED** [review]

**Pull request merged**
