### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by ShriprajwalK**
Proposal for a pull request template. I've kept it limited to checklists as they are easy to fill. Addresses part of #2

### CODE REVIEW

**Review by MadhavJivrajani — COMMENTED** [review]
Since this repo is meant mainly for resources and a few tutorials, will we need tests for the same? 

Maybe have a way for them to mention what type of contribution they are sending in. If its resources or a tutorial or otherwise. 

Ask them to specify if they need help with any part of their contribution, things like that

**Comment by ShriprajwalK** [comment]
Makes sense. I'll change stuff.

**Review by MadhavJivrajani — CHANGES_REQUESTED** [review]
We can remove the check list points for contribution guidelines. 
Another PR can incorporate that once we write it

**Review by MadhavJivrajani — COMMENTED** [review]
I changed the wording in a few places, looks good otherwise, if this looks good to you, I'll go ahead and merge it

**Comment by ShriprajwalK** [comment]
Yeah, looks good.

**Review by MadhavJivrajani — APPROVED** [review]

**Pull request merged**
