### PR TITLE
Jupyter notebook tutorial for pyqubo

### PR DESCRIPTION
**Pull request by Sashe17**
Pyqubo light switch demo

### All Submissions:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/QForestCommunity/launchpad/pulls) for the same update/change?
* [x] The commit message is descriptive enough to convey what you are trying to contribute.

* **What kind of change does this PR introduce?** (Is it a new learning resource, tutorial or something else?)

* **What issue is this tackling?** (Link to an open issue here)

### CODE REVIEW

**Review by MadhavJivrajani — CHANGES_REQUESTED** [review]
A few things: 
- There's a `tutorial_guidelines.md` file which gives a basic format to follow for writing tutorials. Make sure you've gone through that. 
- The topic by itself is complicated in nature and its good that not a lot of complex coding is required for this particular example because of the abstraction provided by pyqubo, but this just means that it needs to be made sure that whatever is put in provides sufficient explanation about what is happening.
- A complete explanation isn't required as such, but the foundational math and concepts are always preferable to have and the remaining part of the concepts, you can provide a link to a resource.
- `Spin` and `solve_ising` are the functions being used. What are ising coeffs, what does it mean?
- What is the light switch game? What does it hope to demonstrate and achieve? 
- Can you put the notebook under the `tutorials` directory instead of `/`?

**Comment by MadhavJivrajani** [comment]
Any update?

**Comment by Sashe17** [comment]
Yes by tomorrow they both will be done

**Comment by MadhavJivrajani** [comment]
Code is committed. Closing PR on account of the same.

**Pull request closed without merging**
